name: Run CI/CD
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Run tests
              uses: devcontainers/ci@v0.3
              with:
                runCmd: pytest
